### ISSUE TITLE
Importing FBX with 2 UVs  causes missing material in generated asset

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#50]
Slot made with 2 UV FBX generates fine if it's alone in the Generated.asset if another slot is added it causes the error. Didn't happen in UMA 1.2.

![screenhunter_381 sep 07 23 39](https://cloud.githubusercontent.com/assets/12765338/9725954/db3a0ca6-55b9-11e5-994f-bd4521c241c2.png)

![screenhunter_382 sep 07 23 39](https://cloud.githubusercontent.com/assets/12765338/9725957/e271fb1e-55b9-11e5-9c50-ad703da5bfd7.png)

**Comment by buronix** [comment]
I have the same issue, its problematic because I debug the error, its in UMA.SkinnedMeshCombiner.CombineMeshes (UMA.UMAMeshData target, .CombineInstance[] sources) (at Assets/Standard Assets/UMA/Core/Scripts/SkinnedMeshCombiner.cs:152)

```cs
if (has_uv2)
{
   if (source.meshData.uv2 != null)
   {
     Debug.Log("Source: Length: " + source.meshData.uv2.Length + " Destination Length: " + uv2.Length +
     " VertexIndex: " + vertexIndex + " vertexCount: " + vertexCount +" UV: "+ source.meshData.uv.Length);
     Array.Copy(source.meshData.uv2, 0, uv2, vertexIndex, vertexCount);
   }
```
and my Debug was : Source: Length: 0 Destination Length: 18760 VertexIndex: 0 vertexCount: 508 UV: 508, but when I checked the problematic meshData it has a uv2 array, Im trying to find the problem but Im new with UMA and its not easy to understand what happens inside, but its something weird cause the source meshdata has no uv2, when I check in the inspector the UmaData it shows the problematic slot without Texture 2, and If I remove manually the slot the error dissapear.
![umadata-error-sword](https://cloud.githubusercontent.com/assets/8542684/12476875/9901cbc0-c02c-11e5-9586-898e1f939b11.jpg)

**Comment by Jaimi** [comment]
Fixed in latest update.
