### ISSUE TITLE
UMA2 U3D crash when switching for android platform

### ISSUE THREAD

**Issue by a250951450** [huika/UMA#55]
1.UMA2 U3D crash when switching for android platform
2.In the android platform, while importing UMA2 U3D no response

**Comment by Jaimi** [comment]
What does this mean? Do you get an error message?

**Comment by Jaimi** [comment]
I've managed to duplicate this, but it is not a UMA issue. The issue is that the textures are quite large, and Unity has to convert them, and this causes Unity to appear to lockup while the conversion is in process.  If you wait long enough, Unity will convert the textures, and start responding again. (took about 20 minutes for me).
